# GoReleaser v2 configuration for Snowflake Emulator
version: 2

# Commands to run before build
before:
  hooks:
    - go mod tidy
    - go mod download

# Build configuration
# Note: DuckDB requires CGO, cross-compilation is not supported
# Only linux/amd64 binary is built; use Docker for other platforms
builds:
  - id: snowflake-emulator
    main: ./cmd/server
    binary: snowflake-emulator

    # CGO is required for DuckDB
    env:
      - CGO_ENABLED=1

    # Only build for linux/amd64 (GitHub Actions runner native platform)
    # For macOS and ARM64, use Docker images instead
    goos:
      - linux

    goarch:
      - amd64

    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

# Archive settings
archives:
  - id: snowflake-emulator-archive
    formats:
      - tar.gz

    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    files:
      - README.md
      - LICENSE
      - CLAUDE.md

# Generate checksum file
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshot build naming
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# CHANGELOG generation
changelog:
  use: github-native

# GitHub Release settings
release:
  github:
    owner: nnnkkk7
    name: snowflake-emulator

  draft: false
  prerelease: auto
  mode: replace

  header: |
    ## Snowflake Emulator {{ .Version }}

    A lightweight, open-source Snowflake emulator built with Go and DuckDB.

    ### Installation

    **Docker (Recommended for all platforms)**:
    ```bash
    docker pull ghcr.io/nnnkkk7/snowflake-emulator:{{ .Version }}
    docker run -p 8080:8080 ghcr.io/nnnkkk7/snowflake-emulator:{{ .Version }}
    ```

    **Binary (Linux x86_64 only)**:
    Download the binary below. For macOS and ARM64, please use Docker.

  footer: |
    ---

    **Full Changelog**: https://github.com/nnnkkk7/snowflake-emulator/compare/{{ .PreviousTag }}...{{ .Tag }}

    **Documentation**: https://github.com/nnnkkk7/snowflake-emulator#readme
